server:
  port: 0   # uses random port

spring:
  application:
    name: bonusservice

  datasource:
    url: jdbc:mysql://localhost:3306/db_blog?serverTimezone=Europe/Vienna
    username: root
  #    password: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

  cloud:
    stream:
      bindings:
        input:
          destination: blog.articles
          content-type: application/json
          group: blog.articles.bonusgroup
      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   # disables peer replication
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true